// export const MENU_FETCH_REQUESTED = 'MENU_FETCH_REQUESTED';

export const FORECAST_REQUESTED = 'FORECAST_REQUESTED';
export const FORECAST_RECIEVED = 'FORECAST_RECIEVED';
export const FORECAST_FAILED = 'FORECAST_FAILED';

export const CITY_STRING_CHANGED = 'CITY_STRING_CHANGED';
export const COORDINATES_REQUESTED = 'COORDINATES_REQUESTED';
export const COORDINATES_RECIEVED = 'COORDINATES_RECIEVED';
export const COORDINATES_FAILED = 'COORDINATES_FAILED';
