// export const MENU_FETCH_REQUESTED = 'MENU_FETCH_REQUESTED';

export const FORECAST_REQUESTED = 'FORECAST_REQUESTED';
export const FORECAST_RECIEVED = 'FORECAST_RECIEVED';
export const FORECAST_FAILED = 'FORECAST_FAILED';
